sources:
  - name: "local"
    kind: "local"
install_path: ".skills"
skills:
  - slug: "zod-v4-patterns"
  - slug: "expo-glass-effect"
  - slug: "gemini-api"
  - slug: "loading-button"
  - slug: "rn-button-component"
  - slug: "watermelondb"
  - slug: "edge-functions"
