sources:
  - name: "local"
    kind: "local"
install_path: ".skills"
skills:
  - slug: "zod-v4-patterns"
  - slug: "gemini-api"
  - slug: "loading-button"
  - slug: "edge-functions"
  - slug: "code-review"
