import * as fs from 'fs';
import * as path from 'path';
import { getInstallPath } from './config.js';
import { listLocalSkills, readSkillMeta } from './fs.js';
import type { SkillMeta } from '../types.js';

/**
 * Generate the SKILLS_INDEX.md content
 */
export function generateIndexContent(skills: SkillMeta[]): string {
  const lines: string[] = [
    '# Available Skills',
    '',
    'This file is auto-generated by the skills CLI. Do not edit manually.',
    '',
  ];

  // Add system skill reference first
  lines.push('## _system (Meta-Skill)');
  lines.push('- **Description:** Instructions for AI agents on how to use the skills system');
  lines.push('- **File:** _system/SKILL.md');
  lines.push('');

  // Add each skill
  for (const skill of skills) {
    lines.push(`## ${skill.slug}`);
    lines.push(`- **Source:** ${skill.registry}`);
    lines.push(`- **Version:** ${skill.version}`);

    if (skill.description) {
      lines.push(`- **Description:** ${skill.description}`);
    }

    if (skill.tags.length > 0) {
      lines.push(`- **Tags:** ${skill.tags.join(', ')}`);
    }

    if (skill.compat.length > 0) {
      lines.push(`- **Compatibility:** ${skill.compat.join(', ')}`);
    }

    lines.push(`- **File:** ${skill.slug}/SKILL.md`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Write the SKILLS_INDEX.md file
 */
export function writeIndex(skills: SkillMeta[]): void {
  const installPath = getInstallPath();
  const indexPath = path.join(installPath, 'SKILLS_INDEX.md');

  const content = generateIndexContent(skills);
  fs.writeFileSync(indexPath, content, 'utf-8');
}

/**
 * Regenerate SKILLS_INDEX.md from installed skills
 */
export function regenerateIndex(): void {
  const slugs = listLocalSkills();
  const skills: SkillMeta[] = [];

  for (const slug of slugs) {
    const meta = readSkillMeta(slug);
    if (meta) {
      skills.push(meta);
    }
  }

  // Sort by slug
  skills.sort((a, b) => a.slug.localeCompare(b.slug));

  writeIndex(skills);
}

/**
 * Read the current index file
 */
export function readIndex(): string | null {
  const installPath = getInstallPath();
  const indexPath = path.join(installPath, 'SKILLS_INDEX.md');

  if (!fs.existsSync(indexPath)) {
    return null;
  }

  return fs.readFileSync(indexPath, 'utf-8');
}
